### ISSUE TITLE
Indigo needs new build dependency on cmake_modules for finding Eigen

### ISSUE THREAD

**Issue by sosswald** [ahornung/humanoid_navigation#13]
FindEigen.cmake has been moved to the cmake_modules package in Indigo, thus the humanoid_localization package needs an additional build dependency on cmake_modules.

There is no indigo-devel branch yet, so I can't create a pull request. See commit https://github.com/sosswald/humanoid_navigation/commit/abb3e7126497f1214491908427decccc311dfda9 in my fork for the changes.

**Comment by ahornung** [comment]
Thanks, fixed and new branch created.
