### ISSUE TITLE
Do you have a plan to release on ROS Kinetic version?

### ISSUE THREAD

**Issue by robotpilot** [ahornung/humanoid_navigation#14]
Hello! I'm a researcher in ROBOTIS. I have a plan to release the Thormang3 packages (kinetic version, http://wiki.ros.org/ROBOTIS-THORMANG3). So, your footstep_planner package is very important for us. Do you have a plan to release on ROS Kinetic version?

**Comment by ahornung** [comment]
I am no longer working actively on the footstep planner, so there are no plans for future releases (from me at least).

**Comment by robotpilot** [comment]
@ahornung 
Thanks for a reply. I think that your packages are very important for the researcher on the humanoid robot. So can I be maintainer your footstep_planner package?

**Comment by ahornung** [comment]
You're welcome to fork the repo and continue developing there.

Note that there hasn't been an official release as catkin package yet.

**Comment by robotpilot** [comment]
Thanks, @ahornung . I truly appreciate your time and effort.

**Comment by AravindaDP** [comment]
@robotpilot I'm also interested in this stack (though I'm specifically interested in costmap_2d package)
Do you have any plans on releasing this through ROS build farm?

**Comment by robotpilot** [comment]
@AravindaDP , I don't care! But, do you know that the "sbpl(http://wiki.ros.org/sbpl)" package is dependency package of this package? It is also not released on Kinect version.

**Comment by AravindaDP** [comment]
@robotpilot So I understand that you have no plans on getting this package released on ros build farm. So I will plan to get this released on ros build farm by submitting a request and will see whether it gets accepted.
Regarding sbpl. My requirement is to get humanoid_navigation released on indigo. Fortunately sbpl is released for that. Later I may see whether I can get these two released on kinetic. Will update if I have any progress on these.

**Comment by AravindaDP** [comment]
Note: I have released this package in indigo through ros build farm and now prebuilt binary packages are available through ros package repository. I'll check if I can release for kinetic as well.

**Comment by AravindaDP** [comment]
@ahornung I have noticed that you have accepted couple of bug fixes after my initial release over ros build farm.
I plan to first merge changes I had to do for a indigo release as a catkin package to your repo before further releasing.
Would you have time to accept if I opened a pull request to your repo?

**Comment by ahornung** [comment]
Sure, although I'm not working on it anymore. So best would be to merge into your repo and release from there.
