### ISSUE TITLE
PlanFootstepsBetweenFeet msg missed

### ISSUE THREAD

**Issue by efernandez** [ahornung/humanoid_navigation#4]
In hydro-devel branch I have the following errors:

<pre>
>>>>>>>> g++ on FootstepPlanner.cpp failed with error: 
In file included from /home/enriquefernandez/catkin_ws/src/humanoid_navigation/footstep_planner/src/FootstepPlanner.cpp:21:0:
/home/enriquefernandez/catkin_ws/src/humanoid_navigation/footstep_planner/include/footstep_planner/FootstepPlanner.h:29:56: fatal error: humanoid_nav_msgs/PlanFootstepsBetweenFeet.h: No such file or directory
</pre>

<pre>
>>>>>>>> g++ on FootstepPlannerNode.cpp failed with error:
In file included from /home/enriquefernandez/catkin_ws/src/humanoid_navigation/footstep_planner/include/footstep_planner/FootstepPlannerNode.h:29:0,
                 from /home/enriquefernandez/catkin_ws/src/humanoid_navigation/footstep_planner/src/FootstepPlannerNode.cpp:21:
/home/enriquefernandez/catkin_ws/src/humanoid_navigation/footstep_planner/include/footstep_planner/FootstepPlanner.h:29:56: fatal error: humanoid_nav_msgs/PlanFootstepsBetweenFeet.h: No such file or directory
</pre>

<pre>
>>>>>>>> g++ on FootstepNavigation.cpp failed with error:
In file included from /home/enriquefernandez/catkin_ws/src/humanoid_navigation/footstep_planner/include/footstep_planner/FootstepNavigation.h:25:0,
                 from /home/enriquefernandez/catkin_ws/src/humanoid_navigation/footstep_planner/src/FootstepNavigation.cpp:21:
/home/enriquefernandez/catkin_ws/src/humanoid_navigation/footstep_planner/include/footstep_planner/FootstepPlanner.h:29:56: fatal error: humanoid_nav_msgs/PlanFootstepsBetweenFeet.h: No such file or directory
</pre>

I have ros-hydro-humanoid-msgs and ros-hydro-humanoid-nav-msgs installed.
I also tried with master and devel branches from the github repo (https://github.com/ahornung/humanoid_msgs).

**Comment by ahornung** [comment]
`devel` branch on humanoid_msgs should work, the srv is there:
https://github.com/ahornung/humanoid_msgs/tree/devel/humanoid_nav_msgs/srv

Anyways, I'll merge on master and create a new release for humanoid_msgs.
